{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Barefoot Nomad ",
    "description": "Barefoot Nomad  Project Application API",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "basePath": "/",
  "tags": [
    {
      "name": "barefoot Nomad company",
      "description": "API for barefoot-Nomad system"
    }
  ],
  "schemes": ["http", "https"],
  "consumes": ["application/json", "form-data"],
  "produces": ["application/json"],

  "paths": {
    "/api/v1/user": {
      "get": {
        "tags": ["user router"],
        "description": "Get user information by id",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": "true",
            "description": "A login jwt token should be passed in the header",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Display user information",
            "schema": {
              "$ref": "#/components/schemas/User_info"
            }
          }
        }
      },
      "put": {
        "tags": ["user router"],
        "description": "Update profile information of user with id=userId.",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": "true",
            "description": " A header that sets the input type of the body",
            "schema": {
              "type": "string",
              "example": "form-data"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": "true",
            "description": "A jason-web-token generated on login and signup should be passed in request header.",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "header",
            "required": true,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "ki"
            }
          },
          {
            "name": "fullname",
            "in": "body",
            "required": false,
            "schema": {
              "type": "string",
              "example": "Gorba Koks"
            }
          },
          {
            "name": "username",
            "in": "body",
            "required": false,
            "schema": {
              "type": "string",
              "example": "warrior"
            }
          },
          {
            "name": "password",
            "in": "body",
            "required": false,
            "schema": {
              "type": "string",
              "example": "password"
            }
          },
          {
            "name": "profilePicture",
            "in": "body",
            "required": false,
            "description": "This should be a file of an imaage",
            "schema": {
              "type": "file",
              "example": "C:/users/user_name/folder_name/image.type"
            }
          }
        ],
        "consumes": ["form-data"],
        "responses": {
          "200": {
            "description": "A message is displayed if updating is successfull and in language specified in header.",
            "schema": {
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Imyirondoro yawe yahinduwe neza."
                }
              }
            }
          }
        }
      }
    },

    "/api/v1/auth/siginIn": {
      "post": {
        "tags": ["user router"],
        "description": "user login",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Accept-Language",
            "in": "header",
            "required": true,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "en"
            }
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "properties": {
                "email": {
                  "type": "string",
                  "example": "strikers668@gmail.vom"
                },
                "password": {
                  "type": "string",
                  "example": "password"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "login successfully",
            "schema": {
              "properties": {
                "message": {
                  "type": "string",
                  "example": "successfully logged in"
                },
                "token": {
                  "type": "string",
                  "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmdWxsbmFtZSI6InVzZXIgb25lIiwiZW1haWwiOiJ1c2Vy"
                }
              }
            }
          }
        }
      }
    },
    "api/user/login/google": {
      "get": {
        "tags": ["user router"],

        "description": "user login with google",
        "parameters": [
          {
            "name": "Accept-Language",
            "in": "header",
            "required": true,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "en"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "login successfully"
          }
        }
      }
    },
    "api/user/login/facebook": {
      "get": {
        "tags": ["user router"],
        "description": "user login with facebook",
        "parameters": [
          {
            "name": "Accept-Language",
            "in": "header",
            "required": true,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "en"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "login successfully"
          }
        }
      }
    },
    "/api/v1/request/comment/{id}": {
      "post": {
        "tags": ["Comments"],
        "description": "Comment on  request",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": "true",
            "description": "A login token should be passed in the headers",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Request ID",
            "type": "string"
          },
          {
            "name": "Comment Details",
            "in": "body",
            "required": true,
            "description": "Submit a comment",
            "schema": {
              "example": {
                "comment": "This is the comment!"
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Comment submitted"
          }
        }
      },
      "get": {
        "tags": ["Comments"],
        "description": "Comments on request",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": "true",
            "description": "A login token should be passed in the headers",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Request ID",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Comments requested"
          }
        }
      }
    },
    "/api/v1/user/signup": {
      "post": {
        "tags": ["user router"],
        "description": "user signup",
        "parameters": [
          {
            "name": "Accept-Language",
            "in": "header",
            "required": true,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "en"
            }
          },

          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/User"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Signer Up successfully",
            "schema": {
              "type": "array",
              "$ref": "#/components/schemas/User"
            }
          }
        }
      }
    },

    "/api/v1/user/confirmation/{token}": {
      "post": {
        "tags": ["user router"],
        "description": "user email confirmation",
        "parameters": [
          {
            "name": "Accept-Language",
            "in": "header",
            "required": true,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "en"
            }
          },
          {
            "name": "token",
            "in": "path",
            "required": true,
            "description": "token from email account",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "The account has been verified. Please log in.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    },

    "/api/v1/user/resend": {
      "post": {
        "tags": ["user router"],
        "description": "resend confirmation email",
        "parameters": [
          {
            "name": "Accept-Language",
            "in": "header",
            "required": true,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "en"
            }
          },
          {
            "name": "email",
            "in": "body",
            "required": true,
            "description": "email used in registration",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "confirmation email resend succesfully!",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    },

    "/api/v1/auth/forgot_password": {
      "post": {
        "tags": ["user router"],
        "description": "user forget password",
        "parameters": [
          {
            "name": "Accept-Language",
            "in": "header",
            "required": true,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "en"
            }
          },
          {
            "name": "email",
            "in": "body",
            "required": true,
            "description": "email used in registration",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "password reset link has been succesfully sent inbox",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    },
    "/api/v1/reset_password/{token}": {
      "post": {
        "tags": ["user router"],
        "description": "user forget password",
        "parameters": [
          {
            "name": "Accept-Language",
            "in": "header",
            "required": true,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "en"
            }
          },
          {
            "name": "token",
            "in": "path",
            "required": true,
            "description": "token from email account",
            "type": "string"
          },
          {
            "name": "password",
            "in": "body",
            "required": true,
            "description": "new password",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Password is updated successfully",
            "schema": {
              "$ref": "#/components/schemas/UserPassword"
            }
          }
        }
      }
    },
    "/api/v1/user/createRole": {
      "post": {
        "tags": ["Super admin router"],
        "description": "User admin can create new role in the system",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "headers",
            "required": "true",
            "description": " A header that sets the input type of the body",
            "schema": {
              "type": "string",
              "example": "form-data"
            }
          },
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A login jwt token should be passed in the headers to verify if it is SUPER_ADMIN",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "fr"
            }
          },
          {
            "name": "name",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string",
              "example": "Travel Administrator"
            }
          },
          {
            "name": "description",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string",
              "example": "This role helps for administating travels of company employees"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Role must be created if the role exist in the system.",
            "schema": {
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Role is created in the system"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/user/assignRole": {
      "post": {
        "tags": ["Super admin router"],
        "description": "User admin can assign the existing role to any existing user with his/her email address",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "headers",
            "required": "true",
            "description": " A header that sets the input type of the body",
            "schema": {
              "type": "string",
              "example": "form-data"
            }
          },
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A login jwt token should be passed in the headers to verify if it is SUPER_ADMIN",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "fr"
            }
          },
          {
            "name": "email",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string",
              "example": "user1@example.com"
            }
          },
          {
            "name": "userRole",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string",
              "example": "Travel Administrator"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Role must be assigned if the role already exist in the system and is assigned to the existing email in the systme.",
            "schema": {
              "properties": {
                "message": {
                  "type": "string",
                  "example": "role is successifully assigned"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/user/getRoles": {
      "get": {
        "tags": ["Super admin router"],
        "description": "Admin should get all the roles available in the system",
        "parameters": [
          {
            "name": "Authorization",
            "in": "headers",
            "required": "true",
            "description": "A login jwt token should be passed in the headers",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "All availble roles must be fetched and display on the page for admin to see them.",
            "schema": {
              "properties": {
                "roles": [
                  {
                    "id": {
                      "type": "integer",
                      "example": 1
                    },
                    "name": {
                      "type": "string",
                      "example": "Manager"
                    },
                    "description": {
                      "type": "string",
                      "example": "This is for managing trips"
                    },
                    "createdAt": {
                      "type": "string",
                      "example": "2021-01-03T17:12:06.142Z"
                    },
                    "updatedAt": {
                      "type": "string",
                      "example": "2021-01-03T17:12:06.142Z"
                    }
                  },
                  {
                    "id": {
                      "type": "integer",
                      "example": 2
                    },
                    "name": {
                      "type": "string",
                      "example": "Travel Administrator"
                    },
                    "description": {
                      "type": "string",
                      "example": "This is for administtrating travels"
                    },
                    "createdAt": {
                      "type": "string",
                      "example": "2021-01-03T17:12:06.142Z"
                    },
                    "updatedAt": {
                      "type": "string",
                      "example": "2021-01-03T17:12:06.142Z"
                    }
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/user/deleteRole/1": {
      "delete": {
        "tags": ["Super admin router"],
        "description": "Admin can be able to delete any role in the system using its id.",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "headers",
            "required": "true",
            "description": " A header that sets the input type of the body",
            "schema": {
              "type": "string",
              "example": "form-data"
            }
          },
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A jason-web-token generated on login and signup should be passed in request headers.",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "ki"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A message is displayed if deletion is successfull and in language specified in headers.",
            "schema": {
              "type": "string",
              "example": "uruhare rwasibwe neza."
            }
          }
        }
      }
    },
    "/api/v1/user/updateRole/1": {
      "patch": {
        "tags": ["Super admin router"],
        "description": "Admin can be able to update any role in the system using its id.",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "headers",
            "required": "true",
            "description": " A header that sets the input type of the body",
            "schema": {
              "type": "string",
              "example": "form-data"
            }
          },
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A jason-web-token generated on login and signup should be passed in request headers.",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "A header that sets language translation for responses.",
            "schema": {
              "type": "string",
              "example": "en"
            }
          },
          {
            "name": "name",
            "in": "body",
            "required": false,
            "schema": {
              "type": "string",
              "example": "Travel Admin (updated)"
            }
          },
          {
            "name": "description",
            "in": "body",
            "required": false,
            "schema": {
              "type": "string",
              "example": "This is the role that is updated and responsible for administrating travels"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A message is displayed if the update is successfull and in language specified in headers.",
            "schema": {
              "type": "string",
              "example": "The is role updated successfully"
            }
          }
        }
      }
    },
    "/api/v1/user/getRole/2": {
      "get": {
        "tags": ["Super admin router"],
        "description": "Admin should get all the roles available in the system",
        "parameters": [
          {
            "name": "Authorization",
            "in": "headers",
            "required": "true",
            "description": "A login jwt token should be passed in the headers",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "All availble roles must be fetched and display on the page for admin to see them.",
            "schema": {
              "properties": {
                "message": {
                  "type": "string",
                  "example": "role was fetched successfully"
                },
                "roleToFetch": {
                  "id": {
                    "type": "integer",
                    "example": 2
                  },
                  "name": {
                    "type": "string",
                    "example": "Senior Travel Administrator (Updated)"
                  },
                  "description": {
                    "type": "string",
                    "example": "this role is for administrating travels"
                  },
                  "createdAt": {
                    "type": "string",
                    "example": "2021-01-03T17:12:06.142Z"
                  },
                  "updatedAt": {
                    "type": "string",
                    "example": "2021-01-03T17:25:15.160Z"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/trip/one-way": {
      "get": {
        "tags": ["One way trip routes"],
        "description": "Get one way trip details ",
        "parameters": [
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A jason-web-token generated on login and signup should be passed in request headers.",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "This header sets the translation language for responses.",
            "schema": {
              "type": "string",
              "example": "fr"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Display one way trip details",
            "schema": {
              "$ref": "#/components/schemas/oneWayTripRequestDetails"
            }
          }
        }
      },
      "post": {
        "tags": ["One way trip routes"],
        "description": "Create one way trip request",
        "parameters": [
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A jason-web-token generated on login and signup should be passed in request headers.",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "This header sets the translation language for responses.",
            "schema": {
              "type": "string",
              "example": "fr"
            }
          },
          {
            "name": "Content-Type",
            "in": "headers",
            "required": true,
            "description": "This header sets the content-type to application/json",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "tripType": "one-way",
                "departureDate": "2020-12-20",
                "returnDate": "2020-01-12",
                "originId": 1,
                "destinationId": 3,
                "reason": "Going for Christmas holidays"
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "one way trip request created ",
            "schema": {
              "type": "object",
              "example": {
                "message": "Request submitted"
              }
            }
          },
          "400": {
            "description": "When submitting one way trip request fails",
            "schema": {
              "type": "object",
              "example": {
                "message": "Request is not processed, try again!"
              }
            }
          }
        }
      }
    },
    "/api/v1/trip/one-way/{id}": {
      "get": {
        "tags": ["One way trip routes"],
        "description": "Get one way trip request by id ",
        "parameters": [
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A jason-web-token generated on login and signup should be passed in request headers.",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "This header sets the translation language for responses.",
            "schema": {
              "type": "string",
              "example": "fr"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Display one way trip details",
            "schema": {
              "type": "object",
              "example": {
                "id": 1,
                "tripType": "one-way",
                "departureDate": "2021-12-01",
                "returnDate": null,
                "reason": "christmas holidays",
                "userId": 3,
                "status": "pending",
                "createdAt": "2021-11-30T19:14:37.053Z",
                "updatedAt": "2021-11-30T19:14:37.053Z",
                "User": {
                  "type": "object",
                  "example": {
                    "id": 3,
                    "fullname": "user three",
                    "email": "user3@example.com",
                    "username": "user3",
                    "password": "$2b$10$Fwzc52oitlsCJgV3bKzWmuJc7vOnBAVeTWOTSbREUgY8MzYYGdyqG",
                    "profilePicture": "http://res.cloudinary.com/tech-strikers/image/upload/***/**/picture-name.png",
                    "roleId": null,
                    "provider": "local",
                    "isVerified": true,
                    "createdAt": "2021-11-30T19:14:37.053Z",
                    "updatedAt": "2021-11-30T19:14:37.053Z"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["One way trip routes"],
        "description": "Update specific one way trip request by id",
        "parameters": [
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A jason-web-token generated on login and signup should be passed in request headers.",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "This header sets the translation language for responses.",
            "schema": {
              "type": "string",
              "example": "fr"
            }
          },
          {
            "name": "Content-Type",
            "in": "headers",
            "required": true,
            "description": "This header sets the content-type to application/json",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "tripType": "one-way",
                "departureDate": "2020-12-20",
                "returnDate": "2020-01-12",
                "originId": 1,
                "destinationId": 3,
                "reason": "Going for Christmas holidays"
              }
            }
          }
        ],
        "responses": {
          "202": {
            "description": "one way trip request updated successfully",
            "schema": {
              "type": "object",
              "example": {
                "message": "Request updated!"
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["One way trip routes"],
        "description": "delete one way trip request by id ",
        "parameters": [
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A jason-web-token generated on login and signup should be passed in request headers.",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQi"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "This header sets the translation language for responses.",
            "schema": {
              "type": "string",
              "example": "fr"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Oneway trip request has been deleted",
            "schema": {
              "type": "object",
              "example": {
                "message": "Request deleted"
              }
            }
          }
        }
      }
    },
    "/api/v1/return_trip": {
      "post": {
        "tags": ["One way trip routes"],
        "description": "Create return trip request",
        "parameters": [
          {
            "name": "Authorization",
            "in": "headers",
            "required": true,
            "description": "A jason-web-token generated on login and signup should be passed in request headers.",
            "schema": {
              "type": "string",
              "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBleGFtcGxlLmNvbSIsInJvbGVJZCI6bnVsbCwiaWF0IjoxNjExMjk1NzM1LCJleHAiOjE2MTEzODIxMzV9.zCvXNQCi4lbUxOkgrBbN_EBRrXsm7lc-GVHdS_IqtMg"
            }
          },
          {
            "name": "Accept-Language",
            "in": "headers",
            "required": false,
            "description": "This header sets the translation language for responses.",
            "schema": {
              "type": "string",
              "example": "fr"
            }
          },
          {
            "name": "Content-Type",
            "in": "headers",
            "required": true,
            "description": "This header sets the content-type to application/json",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "tripType": "one-way",
                "departureDate": "2021-12-20",
                "returnDate": "20201-01-30",
                "originId": 1,
                "destinationId": 3,
                "reason": "Going for Christmas holidays"
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "return trip request created ",
            "schema": {
              "type": "object",
              "example": {
                "message": "Request submitted"
              }
            }
          },
          "400": {
            "description": "When submitting return trip request fails",
            "schema": {
              "type": "object",
              "example": {
                "message": "Request is not processed, try again!"
              }
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "User": {
          "properties": {
            "username": {
              "type": "string",
              "example": "Warrior"
            },
            "email": {
              "type": "string",
              "example": "strikers668@gmail.vom"
            },
            "password": {
              "type": "string",
              "example": "kaka"
            },
            "roleId": {
              "type": "string",
              "example": "user"
            },
            "fullname": {
              "type": "string",
              "example": "Gorba Koks"
            }
          },
          "required": ["username", "email", "password"]
        },
        "UserPassword": {
          "properties": {
            "password": {
              "type": "string",
              "example": "flora123"
            },
            "confirmPassword": {
              "type": "string",
              "example": "flora123"
            }
          },
          "required": ["password", "confirmPassword"]
        },

        "User_info": {
          "properties": {
            "id": {
              "type": "number",
              "example": "30"
            },
            "fullname": {
              "type": "string",
              "example": "Gorba Koks"
            },
            "email": {
              "type": "string",
              "example": "strikers668@gmail.vom"
            },
            "username": {
              "type": "string",
              "example": "Warrior"
            },
            "role": {
              "type": "string",
              "example": "user"
            },
            "provider": {
              "type": "string",
              "example": "google"
            },
            "profilePicture": {
              "type": "string",
              "example": "http://res.cloudinary.com/**/**/image_name.png"
            },
            "createdAt": {
              "type": "string",
              "format": "date",
              "example": "2020-12-10T12:15:58.809Z"
            },
            "updatedAt": {
              "type": "string",
              "format": "date",
              "example": "2020-12-14T13:15:58.809Z"
            }
          }
        },
        "oneWayTripRequestDetails": {
          "type": "array",
          "example": [
            {
              "id": 1,
              "tripType": "one-way",
              "departureDate": "2021-12-01",
              "returnDate": null,
              "reason": "christmas holidays",
              "userId": 3,
              "status": "pending",
              "createdAt": "2021-11-30T19:14:37.053Z",
              "updatedAt": "2021-11-30T19:14:37.053Z",
              "User": {
                "type": "object",
                "example": {
                  "id": 3,
                  "fullname": "user three",
                  "email": "user3@example.com",
                  "username": "user3",
                  "password": "$2b$10$Fwzc52oitlsCJgV3bKzWmuJc7vOnBAVeTWOTSbREUgY8MzYYGdyqG",
                  "profilePicture": "http://res.cloudinary.com/tech-strikers/image/upload/***/**/picture-name.png",
                  "roleId": null,
                  "provider": "local",
                  "isVerified": true,
                  "createdAt": "2021-11-30T19:14:37.053Z",
                  "updatedAt": "2021-11-30T19:14:37.053Z"
                }
              }
            },
            {
              "id": 2,
              "tripType": "one-way",
              "departureDate": "2021-12-01",
              "returnDate": null,
              "reason": "christmas holidays",
              "userId": 4,
              "status": "pending",
              "createdAt": "2021-11-30T19:14:37.053Z",
              "updatedAt": "2021-11-30T19:14:37.053Z",
              "User": {
                "type": "object",
                "example": {
                  "id": 4,
                  "fullname": "user four",
                  "email": "user4@example.com",
                  "username": "user4",
                  "password": "$2b$10$Fwzc52oitlsCJgV3bKzWmuJc7vOnBAVeTWOTSbREUgY8MzYYGdyqG",
                  "profilePicture": "http://res.cloudinary.com/tech-strikers/image/upload/***/**/picture-name.png",
                  "roleId": null,
                  "provider": "local",
                  "isVerified": true,
                  "createdAt": "2021-11-30T19:14:37.053Z",
                  "updatedAt": "2021-11-30T19:14:37.053Z"
                }
              }
            }
          ]
        }
      }
    }
  }
}
